project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  name: "giantswarm/azure-operator"
  tag: "[[ .Version ]]"
Installation:
  V1:
    Registry:
      Domain: quay.io

# clusterID is dynamic environment value, calculated after cluster creation
# applies only to Giant Swarm clusters
clusterID: "test-cluster"
