orbs:
  architect: giantswarm/architect@2.2.0

version: 2.1
workflows:
  build_and_e2eTest:
    jobs:
      # build operator
      - architect/go-build:
          name: go-build
          binary: k8s-net-prober
          resource_class: large
          filters:
            tags:
              only: /^v.*/

      # build and push docker image to quay.
      - architect/push-to-docker:
          name: push-k8s-net-prober-to-quay
          image: "quay.io/giantswarm/k8s-net-prober"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      # build and push helm chart to app catalog.
      - architect/push-to-app-catalog:
          name: push-to-default-app-catalog
          app_catalog: "default-test-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "k8s-net-prober"
          # Make sure docker image is successfully built.
          requires:
            - push-k8s-net-prober-to-quay
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
